config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/about', to: 'pages#about'
  
  resources :courses do
    resources :progresses, only: [:create, :update]
    resources :comments, only: [:create]
    resources :exercises, only: [:new, :create]

    member do
      get :lecture
      get :video
      get :code
      get :visualization
      get :comments
    end
  end

  resources :comments, only: :update

  resources :users, only: [:edit, :update]

  get '/dashboard', to: 'users#dashboard'
  resources :comments, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="container">
	<%= form_with model: @course, local: true do |form| %>

		<div class="form-inputs">
			<%= form.label :name %><br>
			<%= form.text_field :name, class: "form" %><br>
			<%= form.label :photo %><br>
			<%= form.file_field :photo %><br>
			<%= form.label :images %><br>
			<%= form.file_field :images, multiple: true %><br>
			<%= form.label :description %><br>
			<%= form.text_field :description, class: "form" %><br>
			<%= form.label :short_description %><br>
			<%= form.text_field :short_description, class: "form" %><br>
			<%= form.label :Lecture %><br>
			<div class="lecture">
				<%= form.rich_text_area :body, class: "action-text" %>			
			</div><br>
			<%= form.label :video %><br>
			<%= form.text_field :video, class: "form" %><br>
			<%= form.label :category %><br>
			<%= form.text_field :category, class: "form" %><br>
			<%= form.label :difficulty %><br>
			<%= form.text_field :difficulty, class: "form" %><br>
			<%= form.label :tag_list, label: "Add tags", hint: "Add your tags, separated by commas" %><br>
			<%= form.text_field :tag_list %>
		</div><br>

		<div class="form-actions">
			<%= form.submit%>
		</div>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon m-0">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", "/", class: "nav-link nav-link-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Courses", courses_path, class: "nav-link nav-link-light" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag user_image_url(current_user), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Update Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-banner" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>