config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/about', to: 'pages#about'
  
  resources :courses do
    resources :progresses, only: [:create, :update]
    resources :comments, only: [:create]
    resources :exercises, only: [:new, :create]

    member do
      get :lecture
      get :video
      get :code
      get :visualization
      get :comments
    end
  end

  resources :comments, only: :update

  resources :users, only: [:edit, :update]

  get '/dashboard', to: 'users#dashboard'
  resources :comments, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<div class="container text-center">
  <%= image_tag "logo.png", class: "m-4" %>
</div>



<div class="mt-0 mx-auto w-full md:w-256 max-w-full">
<h3 class="text-lg text-center">AlgoLearning Team</h3>



<div class="container align-center aboutteam">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters align-center">
      <div class="col-md-4">
        <a href="https://github.com/flaviomahoney" target=”_blank”><%= image_tag "Flavio.png", class: "card-img "%></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Flavio Mahoney</h5>
          <p class="card-text"></p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-3 ml-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <a href="https://github.com/Leopyy" target=”_blank”><%= image_tag "Leo.png", class: "card-img" %></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Leonardo Figueira</h5>
          <p class="card-text">Front-Endless guy</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <a href="https://github.com/itamarlewagon" target=”_blank”><%= image_tag "Itamar.png", class: "card-img" %></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Itamar Pereira</h5>
          <p class="card-text"></p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-3 ml-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <a href="https://github.com/vkaraujo" target=”_blank”><%= image_tag "Viktor.png", class: "card-img" %></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Viktor Waissmann</h5>
          <p class="card-text">Blackout</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
<div>


<div class="container text-center">
  <h3>Our Mission</h3>

</div>

app/views/pages/home.html.erb
<% content_for :after_js do %>
  <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/TweenLite.min.js"></script>
  <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/EasePack.min.js"></script>
  <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/demo.js"></script>
<% end %>

<div class="demo banner">
   <div class="content">
      <div id="large-header" class="large-header">
          <canvas id="demo-canvas"></canvas>
          <div class="main-title">
            <h1>AlgoLearning</h1>
            <p class="p-bottom"><span class="thin">Explore our</span> universe</p>
            <p>Learn how to pass on your coding interview!</p>
            <% if current_user %>
              <%= link_to "Discover more", courses_path, class: "btn btn-banner" %>
            <% else %>
              <%= link_to "Discover more", user_session_path, class: "btn btn-banner" %>
            <% end %>
          </div>
      </div>
   </div>
</div>

<div class="cards">
  <a href="#learn">
    <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1504639725590-34d0984388bd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80)">
      <p>Learn</p>
    </div>
  </a>
  <a href="#practice">
    <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
      <p>Practice</p>
    </div>
  </a>
  <a href="#hired">
    <div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1550439062-609e1531270e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
      <p>Get hired!</p>
    </div>
  </a>
</div>

<div class="card-big">
  <div id="learn" class="card-learn">
    <a href="#top"><i class="fa fa-arrow-circle-up"></i></a>
    <h2>Get Prepared for any Coding Interview.</h2>
    <h4>We wil teach you the most used problems asked by top-tier companies.</h4>
    <div class="container-learn">
      <div class="card-category-learn" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
      </div>
      <div class="card-learn-description">
        <p><strong> Algorithms and Interviews:</strong>
        <br>
          The typical algorithms that you would learn in data structures and algorithms class are very common in coding interviews. Showing confidence and succeding on using them can put you one step closer to getting the job you always dreamed for, so AlgoLearn provides free must-know algorithms courses to prepare the users for real coding interviews.
        </p>
      </div>
    </div>
  </div>

  <div id="practice" class="card-practice">
    <div class="container-practice">
      <a href="#top"><i class="fa fa-arrow-circle-up"></i></a>
      <h2>Practice coding with our courses</h2>
      <div class="card-category-home" style="height: 35vh; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1564865878688-9a244444042a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
      </div>
      <div class="card-category-home" style="height: 45vh; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://miro.medium.com/max/3392/0*55SzPDBcS_m_NUPT.png)">
      </div>
      <h4>Join the best developers and test your skills with us!</h4>
    </div>
  </div>

  <div id="hired" class="card-hired">
    <a href="#top"><i class="fa fa-arrow-circle-up"></i></a>
    <h2>The Best Companies Are Waiting for You!</h2>
    <div class="container-hired">
      <div class="card-category-home-hired" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1538688423619-a81d3f23454b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
      <% if current_user %>
        <%= link_to "Boost Confidence Now!", courses_path, class: "btn btn-banner" %>
      <% else %>
        <%= link_to "Boost Confidence Now!", user_session_path, class: "btn btn-banner" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="list-group">
    <h3>AlgoLearning</h3>

    <%= link_to "About", about_path %>
    <a href="#">Stories</a>
    <a href="#">For Business</a>
  </div>

  <div class="list-group">
    <h3>Catalog</h3>

    <a href="#">Full Catalog</a>
    <a href="#">Web Development</a>
    <a href="#">Data Science</a>
  </div>

  <div class="list-group">
    <h3>Languages</h3>

    <a href="#">Ruby</a>
    <a href="#">HTML</a>
    <a href="#">Javascript</a>
  </div>


  <div class="footer-links">
    <a href="https://github.com/" target=”_blank”><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/" target=”_blank”><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/" target=”_blank”><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/login?lang=pt" target=”_blank”><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/" target=”_blank”><i class="fab fa-linkedin"></i></a>
  </div>
</div>