config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/about', to: 'pages#about'
  
  resources :courses do
    resources :progresses, only: [:create, :update]
    resources :comments, only: [:create]
    resources :exercises, only: [:new, :create]

    member do
      get :lecture
      get :video
      get :code
      get :visualization
      get :comments
    end
  end

  resources :comments, only: :update

  resources :users, only: [:edit, :update]

  get '/dashboard', to: 'users#dashboard'
  resources :comments, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :set_course, only: [:show, :edit, :update, :destroy, :visualization, :lecture, :code, :video]

  def index
    if params[:query].present?
      @courses = Course.tagged_with(params[:query])
    else
      @courses = policy_scope(Course).order(created_at: :desc)
    end
  end

  def show
    @courses = policy_scope(Course).order(created_at: :desc).limit(10) - current_user.courses

    authorize @course
    @user = current_user
    @progress = Progress.new
  end
  
  def code
    authorize @course
    @progress = Progress.find_by(user_id: current_user.id, course_id: @course.id)
  end  

  def visualization
    authorize @course
	end

  def lecture
    authorize @course
    respond_to do |format|
      format.html 
      format.pdf { render template: 'courses/article', pdf: 'article'}
      end
  end

  def video
    @comment = Comment.new
    authorize @course
  end

  def new
    @course = Course.new
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    if @course.save
      flash[:success] = "Object successfully created"
      redirect_to @course
    else
      flash[:alert] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    authorize @course
  end

  def update
    authorize @course
    if @course.update(course_params)
      redirect_to @course, notice: 'Course Create Succesfully'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    authorize @course
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :description, :lecture, :code, :video, :dataset, :category, :difficulty, :photo, :body, :tag_list, :short_description, images: [])
  end
end

app/views/courses/_image.html.erb
<div class="card-photo-cp" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), <%= course_image_url(course) %>;">
</div>

app/views/courses/article.pdf.erb
<div class="m-4 d-flex justify-content-between">
  <div class="text-justify">
    <%= @course.body %>
  </div>
</div>

app/views/courses/code.html.erb
<div class="navbar navbar-expand-sm navbar-light bg-light">
    <ul class="navbar-nav">
      <li class="nav-item">
				<%= link_to "Lecture", lecture_course_path(@course) , class: "nav-link nav-link-grey" %>
      </li>
      <li class="nav-item active">
				<strong><%= link_to "Exercise", code_course_path(@course) , class: "nav-link nav-link-dark" %></strong>
      </li>
			<li class="nav-item">
				<%= link_to "Hint", video_course_path(@course) , class: "nav-link nav-link-grey" %>
      </li>
    </ul>
</div>

<div class="container mt-4">
  <%number = 0%>
  <% @course.exercises.each do |element| %>
    <%number = number + 1%>
    <div class="wrap-collabsible">
      <input id="collapsible-<%=element.id%>" class="toggle" type="checkbox">
      <label for="collapsible-<%=element.id%>" class="lbl-toggle d-flex justify-content-center align-items-center" id="margin" tabindex="0">Exercise <%=number%> 
      <% if element.difficulty == "Easy" %>
            <span class="card-tag-exercise easy-exercise ml-3"><%= element.difficulty %></span>
          <% elsif element.difficulty == "Medium" %>
            <span class="card-tag-exercise medium-exercise ml-3"><%= element.difficulty %></span>
          <% elsif element.difficulty == "Hard" %>
            <span class="card-tag-exercise hard-exercise ml-3"><%= element.difficulty %></span>
          <% end %> 
      </label>
      <div class="collapsible-content">
        <div class="content-inner">
          <%= element.code%>
          To do the exercise: <a href="https://repl.it/languages/ruby" target="_blank">Click Here</a>
        </div>
      </div>
    </div>
  <%end%>

 
    <%= link_to "Conclude Course!", course_progress_path(@course, @progress, progress: {status: "Finished"}), class: "btn btn-conclude", method: :patch  %>
   

</div>

app/views/courses/edit.html.erb
<div class="container">
  <h1>Update Course Information</h1>
  <%= render 'shared/form', course: @course %>
  <%= link_to 'Back', courses_path%>
</div>

app/views/courses/index.html.erb
<div class="container mt-3">
  <div class="inline-block d-flex" >
   <div style="width: 375px">
    <%= form_tag courses_path, method: :get do %>
      <%= select_tag :query, options_for_select(ActsAsTaggableOn::Tag.pluck(:name)),
        class: "form-control select2",
        multiple: "multiple",
        placeholder: "Find a course"
      %></div>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <br>
  <% if policy(Course).create? %>
   <%= link_to 'Add Course', new_course_path, class: "btn btn-blue mb-3" %>
  <% end %>

  <div class="cards">
    <% @courses.each do |course| %>
      <%= link_to course do %>
        <div class= "cards-course">
        	<img class="card-photo-cp" src="<%= course_image_url(course) %>" alt="">
        	<div class="card-info">
      			<h2><%= course.name %></h2>
            <p><%= course.short_description %></p>
      		</div>
          <div class="card-tag-box">
            <p class="comment-counter-box"> <%= course.comments.count %> <i class="far fa-comment-alt"></i></p>
            <p class="card-tag"><%= course.category %></p>
      	    <% if course.difficulty == "Easy" %>
              <p class="card-tag easy"><%= course.difficulty %></p>
            <% elsif course.difficulty == "Medium" %>
              <p class="card-tag medium"><%= course.difficulty %></p>
            <% elsif course.difficulty == "Hard" %>
              <p class="card-tag hard"><%= course.difficulty %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/courses/lecture.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">
      <li class="nav-item active">
				<strong><%= link_to "Lecture", lecture_course_path(@course) , class: "nav-link nav-link-dark" %></strong>
      </li>
      <li class="nav-item">
				<%= link_to "Exercise", code_course_path(@course) , class: "nav-link nav-link-grey" %>
      </li>
			<li class="nav-item">
				<%= link_to "Hint", video_course_path(@course) , class: "nav-link nav-link-grey" %>
      </li>
    </ul>
</div>

<div class="m-4 d-flex justify-content-between">
  <iframe id="article" src="http://localhost:3000/courses/<%= @course.id %>/lecture.pdf" frameborder="0"></iframe>
  <% if @course.images.any? %>
    <div class="card-carousel-vis ml-4 ">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @course.images.each_with_index do |image, index| %>
            <% css_class = "carousel-item text-center active" if index == 0 %>
            <% css_class ||= "carousel-item text-center" %>
            <div class="<%= css_class %>">
              <%= cl_image_tag image.key, class: "flex-column" %>
            </div>  
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <div class="carousel-arrow-box">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </div>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <div class="carousel-arrow-box">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </div>
        </a>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="container">
<h1>New Course</h1>

<%= render 'shared/form', course: @course %>

<%= link_to 'Back', courses_path%>
</div>

app/views/courses/show.html.erb
<div class="container mt-4 w-75">
  <div class="d-flex">
    <div class="sidebar-courses">
      <h2>Courses</h2>
      
      <div class="courses-section">
        <div class="chat-section-header">
          <h4>Enrolled</h4>
        </div>
        <% @user.progresses.each do |progress| %>
          <%= link_to progress.course do %>
            <div class="channel">
              <span><i class="fa fa-play-circle"></i> <%= progress.course.name %></span>
            </div>
          <% end %>
        <% end %>
      </div>
        
      <div class="courses-section">
        <div class="chat-section-header">
          <h4>Other courses</h4>
        </div>
        <% @courses.each do |course| %>
          <%= link_to course do %>
            <div class="channel">            
              <span><i class="fa fa-circle"></i> <%= course.name %></span>
            </div>
          <% end %>
        <% end %>        
      </div>
      
    </div>
    <div class="w-75">
      <div class="w-100 mb-3">
        <div class="card-category-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= course_image_url(@course) %>')">
        <%= @course.name %>
        </div>
      </div>
      <div class="p-show">
        <p><%= @course.description %></p>
        <p><strong>Category: </strong><%= @course.category %></p>
        <p><strong>Difficulty: </strong><%= @course.difficulty %></p>
      </div>
      
    
      <% if policy(Course).lecture? && @user.courses.include?(@course) %>
        <%= link_to "Resume Our Class", lecture_course_path, class: "btn btn-blue" %>
      <% elsif policy(Course).lecture? && policy(Progress).create? %>
          <%= simple_form_for [@course, Progress.new] do |f| %>
            <div class="form-actions">
              <%= f.button :submit , value: 'Join Our Class', class: "btn btn-blue"%>
            </div>
          <% end %>
      <% else %>
      <% end %>
    
      <% if policy(Course).update? %>
        <%= link_to "Update", edit_course_path(@course), class: "btn btn-green" %>
      <% end %>
    
      <% if policy(Course).destroy? %>
        <%= link_to course_path(@course), class: "btn btn-red", method: :delete, data: { confirm: 'Are you sure?' } do %>
              Remove <i class="fas fa-trash"></i>
            <% end %>
      <% end %>
    
      <% if policy(Exercise).create? %>
      <%= link_to 'Add Exercise', new_course_exercise_path(@course), class: "btn btn-blue" %>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/video.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">
      <li class="nav-item">
				<%= link_to "Lecture", lecture_course_path(@course) , class: "nav-link nav-link-grey" %>
      </li>
      <li class="nav-item">
				<%= link_to "Exercise", code_course_path(@course) , class: "nav-link nav-link-grey" %>
      </li>
			<li class="nav-item active">
				<strong><%= link_to "Hint", video_course_path(@course) , class: "nav-link nav-link-dark" %></strong>
      </li>
    </ul>
</div>


<div class='videobox mt-4'>

  <iframe class="videobox" src= "<%= @course.video %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<div class="container comments-box mt-4">

  <div text-center>

    <%= simple_form_for [@course, Comment.new] do |f| %>

      <div class="form-inputs">
        <%= f.input :description, label: 'New Comment:' %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-blue", label: 'Comment', value: "Comment" %>
      </div>
    <% end %>
    <br>
    <% if @course.comments.count != 0 %>
      <% @course.comments.each do |comment| %>
        <div class="comment-box" id="comment-<%= comment.id %>">
          <div class="mr-2">
            <%= image_tag user_image_url(comment.progress.user), class: "comment-avatar" %>
          </div>
          <div class="comment-container">
            <div class="d-flex mt-2 mb-2">
              <i class="author">
                <span class= "mr-2">
                  <span><%= comment.progress.user.username %></span>
                  <small><%= comment.created_at.in_time_zone(-3).strftime("%a %b %e at %H:%M") %>
                </span>
                <span class= "mr-2">
                  <%= link_to comment_path(comment, vote: :upvote), method: :patch, remote:true do %>
                    <i class="far fa-thumbs-up" style="color: green"></i>
                  <% end %>
                  <%= comment.get_likes.size %>
                </span>
                <span class= "mr-2">
                  <%= link_to comment_path(comment, vote: :downvote), method: :patch, remote:true  do %>
                    <i class="far fa-thumbs-down" style="color: red"></i>
                  <% end %>
                  <%= comment.get_dislikes.size %>
                </span>

                  <% if comment.progress.user == current_user  %>
                    <span class= "mr-2">
                      <%= link_to comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "white-box" do %>
                        <i class="fas fa-trash"></i>
                      <% end %>
                    </span>
                  <% end %>
                </span>

                </small>
              </i>
            </div>
            <div class="mb-2">
              <%= comment.description %>
            </div>
          </div>
        </div>
      <% end %>
      <div id="last_comment"></div>
    <% end %>
  </div>
</div>

app/views/courses/visualization.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
				<%= link_to "Lecture", lecture_course_path , class: "nav-link nav-link-grey" %>
        <%# <a class="nav-link" href="">Lecture <span class="sr-only">(current)</span></a> %>
      </li>
      <li class="nav-item active">
				<strong><%= link_to "Slides", visualization_course_path , class: "nav-link nav-link-dark" %></strong>
        <%# <a class="nav-link" href="#">Visualization</a> %>
      </li>
      <li class="nav-item">
				<%= link_to "Exercise", code_course_path , class: "nav-link nav-link-grey" %>
        <%# <a class="nav-link" href="#">Exercise(Code)</a> %>
      </li>
			<li class="nav-item">
				<%= link_to "Hint", video_course_path , class: "nav-link nav-link-grey" %>
        <%# <a class="nav-link" href="#">Video(Hint)</a> %>
      </li>

    </ul>
  </div>
</div>